# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.unsafe.configuration-cache=false

mapping_channel=official

mapping_version=1.20.1

minecraft_version=1.20.1

minecraft_version_range=[1.20.1,1.21)

forge_version=47.4.0

forge_version_range=[47,)

loader_version_range=[47,)


mod_id=better_raid

mod_name=Better Raid

mod_license=MIT

mod_version=2101.1.0

mod_group_id=com.chen1335.betterRaid

mod_authors=chen_1335, Flechazo

mod_description=Example mod description.\nNewline characters can be used and will be replaced properly.
